name: deploy ansible and run ansible playbook

on:
  push:
    branches: [feature/init, main]

jobs:  
  ansible-lint-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    # - name: Set up Ansible
    #   run: |
    #     sudo apt-get -y update; \
    #     sudo apt-get -y install ansible; \
    #     ansible --version

    - name: Connect to Azure VM 
      run: |
        ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa <<< y 
        ls -a /home/runner/
        ls /home/runner/.ssh/
        yamini=${{ secrets.AZURE_PEM }} 
        echo yamini >> test.pem              
        chmod 400 test.pem
        ll
        ssh -i test.pem azureuser@20.103.151.129  
        

    # - name: testing ansible ping
    #   run: ansible all -i 20.103.151.129
                      
    # - name: Lint Ansible Playbook
    #   uses: ansible/ansible-lint-action@main
    #   with:
    #     targets: "main.yaml"
  
  # deploy-ansible-playbook:
  #   #needs: ansible-lint-check
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1

  #   - name: Running playbook
  #     run: ansible-playbook main.yaml

  #   - name: checking status 
  #     run: sudo systemctl status apache2   



