name: deploy ansible and run ansible playbook

on:
  push:
    branches: [feature/init, main]

jobs:  
  ansible-lint-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
          path: to_deploy 
    
    - name: Set up Ansible
      run: |
        sudo apt-get -y update; \
        sudo apt-get -y install ansible; \
        ansible --version

    - name: Connect to Azure VM 
      run: |
        ls             
        PEM_KEY=${{ secrets.AZURE_PEM }} 
        echo PEM_KEY >> PEM_KEY.pem              
        chmod 400 PEM_KEY.pem
        ls to_deploy
       
      
        

    # - name: testing ansible ping
    #   run: ansible all -i 20.103.151.129
                      
    # - name: Lint Ansible Playbook
    #   uses: ansible/ansible-lint-action@main
    #   with:
    #     targets: "main.yaml"
  
  # deploy-ansible-playbook:
  #   #needs: ansible-lint-check
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1

  #   - name: Running playbook
  #     run: ansible-playbook main.yaml

  #   - name: checking status 
  #     run: sudo systemctl status apache2   



